WebApplication/ViewModels/SongViewModel.cs
using System;
using System.Web;
using System.ComponentModel;
using CW.Soloist.CompositionService.Midi;
using CW.Soloist.DataAccess.DomainModels;
using CW.Soloist.CompositionService.Enums;
using CW.Soloist.WebApplication.Validations;
using System.ComponentModel.DataAnnotations;


namespace CW.Soloist.WebApplication.ViewModels
{
    public class SongViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(30)]
        [DisplayName("Song Name")]
        public string Title { get; set; }

        [Required]
        [StringLength(70)]
        public string Artist { get; set; }

        [DisplayName("Description")]
        public string Description { get; set; }

        [Required]
        [FileUploadValidation]
        [DisplayName("MIDI File")]
        public HttpPostedFileBase MidiFileHandler { get; set; }

        [DisplayName("MIDI File Name")]
        public string MidiFileName { get; set; }

        [DisplayName("MIDI Playback File")]
        public string MidiPlaybackFileName { get; set; }

        public IMidiFile MidiData { get; set; }

        [Required]
        [DisplayName("Melody Track Number")]
        public MelodyTrackIndex? MelodyTrackIndex { get; set; }
        public string MelodyTrackIndexDescription
        {
            get => MelodyTrackIndex?.GetDisplayName() ??
                CW.Soloist.CompositionService.Midi.MelodyTrackIndex.NoMelodyTrackInFile
                .GetDisplayName();
        }

        [Required]
        [FileUploadValidation]
        [DisplayName("Chords File")]
        public HttpPostedFileBase ChordsFileHandler { get; set; }

        [DisplayName("Chords File Name")]
        public string ChordsFileName { get; set; }

        [DisplayName("Chord Progression")]
        public String ChordProgression { get; set; }

        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }

        [DisplayName("Is Song Public To All Users")]
        public bool IsPublic { get; set; }

        public bool IsUserAuthorizedToEdit { get; set; }
        public bool IsUserAuthorizedToDelete { get; set; }
        public bool IsAdminUser { get; set; }

        public string StatusMessage { get; set; }

        public SongViewModel() { }

        public SongViewModel(Song song)
        {
            Id = song.Id;
            Artist = song.Artist;
            Title = song.Title;
            MidiFileName = song.MidiFileName;
            MidiPlaybackFileName = song.MidiPlaybackFileName;
            ChordsFileName = song.ChordsFileName;
            IsPublic = song.IsPublic;
            Created = song.Created;
            Modified = song.Modified;
            MelodyTrackIndex = song.MelodyTrackIndex;
        }
    }
}

WebApplication/Controllers/CompositionController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using System.Web.UI.WebControls;
using System.Collections.Generic;
using CW.Soloist.DataAccess.UnitOfWork;
using CW.Soloist.DataAccess.DomainModels;
using CW.Soloist.WebApplication.ViewModels;
using CW.Soloist.CompositionService;
using CW.Soloist.CompositionService.Midi;
using CW.Soloist.CompositionService.Enums;
using CW.Soloist.CompositionService.Composers;
using CW.Soloist.CompositionService.MusicTheory;
using CW.Soloist.CompositionService.Composers.GeneticAlgorithm;

namespace CW.Soloist.WebApplication.Controllers
{
    /// <summary>
    /// Controller responsible for managing requests for composing melodies.
    /// </summary>
    public class CompositionController : Controller
    {
        #region Private Instance Fields
        private IMidiFile _midiFile; // used for the composed melody output file
        private IUnitOfWork _databaseGateway; // abstract gateway to the underlying database
        private IEnumerable<PitchRecord> _pitchSelectList; // internal sequence for structuring data to view  
        #endregion

        #region Constructor
        /// <summary> Constructs a composition controller by injecting a 
        /// instance of the unit of work dependency. </summary>
        /// <param name="unitOfWork"> database gateway that manages the in-memory updates to persisted entities.</param>
        public CompositionController(IUnitOfWork unitOfWork)
        {
            // use the injected dependency on the abstract unit of work
            _databaseGateway = unitOfWork;

            // build pitch selection list without hold and rest notes 
            _pitchSelectList = Enum.GetValues(typeof(NotePitch)).Cast<NotePitch>()
               .Except(new[] { NotePitch.HoldNote, NotePitch.RestNote })
               .Select(notePitch => new PitchRecord
               {
                   Pitch = notePitch,
                   Description = notePitch.GetDisplayName()
               });
        }
        #endregion

        #region Compose;    GET: Composition/Compose/<optional songId>
        [HttpGet]
        public async Task<ActionResult> Compose(int? songId = null)
        {
            // fetch id of current logged-in user (if user is indeed logged-in...)
            string userId = User?.Identity?.GetUserId();

            // fetch songs from db according to user's privilages  
            List<Song> authorizedSongs = User?.IsInRole(RoleName.Admin) ?? false
                ? await _databaseGateway.Songs.GetAllAsync()
                : await _databaseGateway.Songs.FindAsync(s => s.IsPublic || s.UserId.Equals(userId));

            // project artist and song name from song list and sort the list accordingly
            var sortedProjectedSongs = authorizedSongs.Select(s => new
            {
                Id = s.Id,
                Title = s.Artist + " - " + s.Title
            }).OrderBy(s => s.Title).ToList();

            // if user requested a specific song, select it
            int? selectedSongId = authorizedSongs.Exists(s => s.Id == songId)
                ? songId
                : authorizedSongs.FirstOrDefault()?.Id;

            // build select list for the songs
            SelectList songSelectList = new SelectList(sortedProjectedSongs, "Id", "Title", songId);

            // build a view model with the prebuilt song list 
            CompositionViewModel viewModel = new CompositionViewModel
            {
                SongSelectList = songSelectList,
                MusicalInstrument = MusicalInstrument.ElectricGrandPiano,
                OverallNoteDurationFeel = OverallNoteDurationFeel.Medium,
                PitchSelectList = new SelectList(_pitchSelectList, "Pitch", "Description"),
                MinPitch = NotePitch.C4,
                MaxPitch = NotePitch.G6,
                useExistingMelodyAsSeed = false
            };

            // pass the view model to the view to render
            return View(viewModel);
        }
        #endregion

        #region Compose;    POST: Composition/Compose
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Compose(CompositionViewModel model)
        {
            // validate that sum of weights is equal to 100
            double weightSum = model.WeightSum;
            if (weightSum != 100)
            {
                string errorMessage =
                    $"The total weights of all fitness function " +
                    $"evaluators must sum up to 100.\n" +
                    $"The current sum is {weightSum}";
                this.ModelState.AddModelError(nameof(model.AccentedBeats), errorMessage);
            }
            
            // assure all other validations passed okay 
            if (!ModelState.IsValid)
            {
                CompositionViewModel viewModel = new CompositionViewModel
                {
                    SongSelectList = new SelectList(_databaseGateway.Songs.GetAll().OrderBy(s => s.Title), nameof(Song.Id), nameof(Song.Title)),
                    PitchSelectList = new SelectList(_pitchSelectList, nameof(PitchRecord.Pitch), nameof(PitchRecord.Description)),
                };
                return View(viewModel);
            }

            // fetch song from datasource  
            Song song = _databaseGateway.Songs.Get(model.SongId);

            // get the chord and file paths on the file server
            string chordFilePath = await SongsController.GetSongPath(song.Id, _databaseGateway, User, SongFileType.ChordProgressionFile);
            string midiFilePath = await SongsController.GetSongPath(song.Id, _databaseGateway, User, SongFileType.MidiOriginalFile);

            // create a compositon instance 
            CompositionContext composition = new CompositionContext(
                chordProgressionFilePath: chordFilePath,
                midiFilePath: midiFilePath,
                melodyTrackIndex: song.MelodyTrackIndex);

            // build evaluators weights 
            MelodyEvaluatorsWeights weights = new MelodyEvaluatorsWeights
            {
                AccentedBeats = model.AccentedBeats,
                ContourDirection = model.ContourDirection,
                ContourStability = model.ContourStability,
                DensityBalance = model.DensityBalance,
                ExtremeIntervals = model.ExtremeIntervals,
                PitchRange = model.PitchRange,
                PitchVariety = model.PitchVariety,
                SmoothMovement = model.SmoothMovement,
                Syncopation = model.Syncopation
            };

            // Compose some melodies and fetch the best one 
            IMidiFile midiFile = composition.Compose(
                strategy: CompositionStrategy.GeneticAlgorithmStrategy,
                overallNoteDurationFeel: model.OverallNoteDurationFeel,
                musicalInstrument: model.MusicalInstrument,
                minPitch: model.MinPitch,
                maxPitch: model.MaxPitch,
                useExistingMelodyAsSeed: model.useExistingMelodyAsSeed,
                customParams: weights)
                .FirstOrDefault();

            // save the midifile output internally 
            _midiFile = midiFile;
            ViewBag.MidiFile = midiFile;

            // save file on the file server  
            string directoryPath = HomeController.GetFileServerPath() + "Outputs" + 
                Path.DirectorySeparatorChar + song.Id + Path.DirectorySeparatorChar;
            Directory.CreateDirectory(directoryPath);
            string filePath = _midiFile.SaveFile(outputPath: directoryPath);

            // return the file to the client client for downloading 
            string fileName = Path.GetFileName(filePath);
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
        #endregion

        #region GetOutputParentPath
        /// <summary>
        /// Gets the parent path on the hosting file server that contains the output 
        /// midi files of the generated composed melodies for all songs.
        /// </summary>
        /// <returns> The path of the parent output directory on the hosting file server. </returns>
        internal static string GetOutputParentPath()
        {
            // returns ~<FileServerPath>\Outputs\
            return HomeController.GetFileServerPath() + "Outputs" + Path.DirectorySeparatorChar;
        }
        #endregion

        #region GetSongOutputPath
        /// <summary>
        /// Gets the path on the hosting file server that contains the output 
        /// midi files of the generated composed melodies for the given song.
        /// </summary>
        /// <param name="songId">The id of the subject song.</param>
        /// <returns> The path of the given song output directory on the hosting file server. </returns>
        internal static string GetSongOutputPath(int songId)
        {
            // returns ~<Parent Path>\<songId>\
            return GetOutputParentPath() + songId + Path.DirectorySeparatorChar;
        }
        #endregion

        #region PitchRecord Internal Private Class
        /// <summary>
        /// Private internal class used for structing pitches for selection in views.
        /// </summary>
        private class PitchRecord
        {
            public NotePitch Pitch { get; set; }
            public string Description { get; set; }
        }
        #endregion
    }
}

WebApplication/Views/Songs/Delete.cshtml
@using CW.Soloist.WebApplication.Controllers;
@model CW.Soloist.WebApplication.ViewModels.SongViewModel

@{
    ViewBag.Title = "Delete Song";
    string termStyle = "text-align: left; color:#b6ff00;";
    CultureInfo timeStampCulture = CultureInfo.CreateSpecificCulture("en-DE");
    string collapseStyle = "color:#b6ff00; background-color:transparent; border-color:yellow;";
}

<h1 style="color:gold">@ViewBag.Title</h1>

<h3>Are you 100% <b><i> sure</i></b> you want to delete this song?</h3>
<div>
    @* Conditional error message *@
    <div class="alert-danger"> @ViewBag.ErrorMessage </div>

    <!-- Song Artist and Title -->
    <div>
        <dl class="dl-horizontal">
            <!-- Artist -->
            <dt style="@termStyle">@Html.DisplayNameFor(m => m.Artist)</dt>
            <dd> @Html.DisplayFor(m => m.Artist)</dd>

            <!-- Song Title -->
            <dt style="@termStyle">@Html.DisplayNameFor(m => m.Title) </dt>
            <dd> @Html.DisplayFor(m => m.Title)</dd>
        </dl>
    </div>

    <!-- Desciprtion List of The Additional Properties   -->
    <div>
        <button type="button" class="collapsible" style="@collapseStyle">Display/Toggle Song Properties </button>
        <div style="display:none">
            <dl class="dl-horizontal">
                <!-- Chord Progression File -->
                <dt style="@termStyle"> @Html.DisplayNameFor(m => m.ChordsFileHandler) </dt>
                <dd> @Html.ActionLink(Model.ChordsFileName, nameof(SongsController.DownloadFile), new { id = Model.Id, songFileType = SongFileType.ChordProgressionFile })</dd>

                <!-- Original MIDI File -->
                <dt style="@termStyle"> @Html.DisplayNameFor(m => m.MidiFileHandler) </dt>
                <dd> @Html.ActionLink(Model.MidiFileName, nameof(SongsController.DownloadFile), new { id = Model.Id, songFileType = SongFileType.MidiOriginalFile }) </dd>

                <!-- Playback MIDI File -->
                <dt style="@termStyle">@Html.DisplayNameFor(m => m.MidiPlaybackFileName) </dt>
                <dd> @Html.ActionLink(Model.MidiPlaybackFileName, nameof(SongsController.DownloadFile), new { id = Model.Id, songFileType = SongFileType.MidiPlaybackFile })</dd>

                @{
                    if (Model.MidiData != null)
                    {
                        <!-- Key Signature -->
                        <dt style="@termStyle"> Key Signature </dt>
                        <dd> @Model.MidiData.KeySignature.ToString() </dd>

                        <!-- Number Of Bars -->
                        <dt style="@termStyle"> Number Of Bars </dt>
                        <dd>  @Model.MidiData.NumberOfBars </dd>

                        <!-- BPM -->
                        <dt style="@termStyle"> Beats Per Minute </dt>
                        <dd>  @Model.MidiData.BeatsPerMinute </dd>

                        <!-- Lowest Pitch -->
                        <dt style="@termStyle"> Lowest Pitch </dt>
                        <dd>  @Model.MidiData.LowestPitch.GetDisplayName() </dd>

                        <!-- Highest Pitch -->
                        <dt style="@termStyle"> Highest Pitch </dt>
                        <dd>  @Model.MidiData.HighestPitch.GetDisplayName() </dd>
                    }
                }

                <!-- Melody Track Index -->
                <dt style="@termStyle">@Html.DisplayNameFor(m => m.MelodyTrackIndex)</dt>
                <dd>  @Model.MelodyTrackIndexDescription </dd>

                <!-- Created -->
                <dt style="@termStyle"> @Html.DisplayNameFor(m => m.Created)</dt>
                <dd>  @Model.Created.ToString("F", timeStampCulture) </dd>

                <!-- Modified -->
                <dt style="@termStyle"> @Html.DisplayNameFor(m => m.Modified)</dt>
                <dd>  @Model.Modified.ToString("F", timeStampCulture) </dd>
            </dl>
        </div> <br /> <br />
    </div>

    <!-- MIDI Tracks Table -->
    <div>
        @{
            if (Model.MidiData != null)
            {
                <button type="button" class="collapsible" style="@collapseStyle">Display/Toggle MIDI Tracks</button>
                <div style="display:none">
                    <table class="table table-bordered table-responsive table-hover">
                        <thead>
                            <tr style="color:gold">
                                <th> Track Number </th>
                                <th> Track Name </th>
                                <th> Instrument Description </th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 1; i < Model.MidiData?.Tracks.Count; i++)
                            {
                                var track = Model.MidiData?.Tracks[i];
                                <tr>
                                    <td> @track.TrackNumber </td>
                                    <td> @track.TrackName </td>
                                    <td> @track.InstrumentName </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <br /> <br />
            }
        }
    </div>

    <!-- Chord Progression Text Area -->
    <div>
        @{
            if (!string.IsNullOrEmpty(Model.ChordProgression))
            {
                <button type="button" class="collapsible" style="@collapseStyle">Display/Toggle Chord Progression</button>
                <div style="display:none">
                    @Html.TextAreaFor(m => m.ChordProgression, 16, 80, new { @class = "green-border-focus", Style = "max-width: 40%; overflow=auto;", Spellcheck = "false", Readonly = true });
                </div>
                <br /><br />
            }
        }
    </div>

    <!-- Delete Form -->
    <div>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete  " class="btn btn-danger btn-lg" />
            </div>
        }
    </div>

    <!-- Footer Links -->
    <div>
        <footer>
            <br />
            <!-- Compose -->
            <text> || </text>
            @Html.ActionLink("Compose ♫♪", "Compose", "Composition", new { songId = Model.Id }, null)
            <text> || </text>

            <!-- Details -->
            @Html.ActionLink("Details", "Details", new { id = Model.Id }) <text>||</text>

            <!-- Edit -->
            @if (Model.IsUserAuthorizedToEdit)
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) <text>||</text>
            }

            <!-- Index -->
            @Html.ActionLink("Back to Song List", "Index") <text> || </text>
        </footer>
    </div>
</div>

<!-- js for handling collapisble elements -->
<script>
    let collapsibleElement = document.getElementsByClassName("collapsible");
    let i;

    for (i = 0; i < collapsibleElement.length; i++) {
        collapsibleElement[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            }
            else {
                content.style.display = "block";
            }
        });
    }
</script>

WebApplication/Views/Songs/Details.cshtml
@using CW.Soloist.CompositionService.Enums;
@using CW.Soloist.WebApplication.Controllers;
@model CW.Soloist.WebApplication.ViewModels.SongViewModel


@{
    ViewBag.Title = "Song Details";
    string termStyle = "text-align: left; color:#b6ff00;";
    CultureInfo timeStampCulture = CultureInfo.CreateSpecificCulture("en-DE");
    string collapseStyle = "color:#b6ff00; background-color:transparent; border-color:yellow;";
}

<!-- Header Title -->
<div>
    <h2 style="color:lightgreen">@Model.StatusMessage</h2>
    <h1 style="color:gold">@ViewBag.Title</h1>
</div>

<!-- Property Desciprtion List  -->
<div>
    <hr />
    <dl class="dl-horizontal">
        <!-- Artist -->
        <dt style="@termStyle">@Html.DisplayNameFor(m => m.Artist)</dt>
        <dd> @Html.DisplayFor(m => m.Artist)</dd>

        <!-- Song Title -->
        <dt style="@termStyle">@Html.DisplayNameFor(m => m.Title) </dt>
        <dd> @Html.DisplayFor(m => m.Title)</dd>

        <!-- Chord Progression File -->
        <dt style="@termStyle"> @Html.DisplayNameFor(m => m.ChordsFileHandler) </dt>
        <dd> @Html.ActionLink(Model.ChordsFileName, nameof(SongsController.DownloadFile), new { id = Model.Id, songFileType = SongFileType.ChordProgressionFile })</dd>

        <!-- Original MIDI File -->
        <dt style="@termStyle"> @Html.DisplayNameFor(m => m.MidiFileHandler) </dt>
        <dd> @Html.ActionLink(Model.MidiFileName, nameof(SongsController.DownloadFile), new { id = Model.Id, songFileType = SongFileType.MidiOriginalFile }) </dd>

        <!-- Playback MIDI File -->
        <dt style="@termStyle">@Html.DisplayNameFor(m => m.MidiPlaybackFileName) </dt>
        <dd> @Html.ActionLink(Model.MidiPlaybackFileName, nameof(SongsController.DownloadFile), new { id = Model.Id, songFileType = SongFileType.MidiPlaybackFile })</dd>

        @* MidiData properties: assure midi data exists *@
        @{
            if (Model.MidiData != null)
            {
                <!-- Key Signature -->
                <dt style="@termStyle"> Key Signature </dt>
                <dd> @Model.MidiData.KeySignature.ToString() </dd>

                <!-- Number Of Bars -->
                <dt style="@termStyle"> Number Of Bars </dt>
                <dd>  @Model.MidiData.NumberOfBars </dd>

                <!-- BPM -->
                <dt style="@termStyle"> Beats Per Minute </dt>
                <dd>  @Model.MidiData.BeatsPerMinute </dd>

                <!-- Lowest Pitch -->
                <dt style="@termStyle"> Lowest Pitch </dt>
                <dd>  @Model.MidiData.LowestPitch.GetDisplayName() </dd>

                <!-- Highest Pitch -->
                <dt style="@termStyle"> Highest Pitch </dt>
                <dd>  @Model.MidiData.HighestPitch.GetDisplayName() </dd>
            }
        }

        <!-- Melody Track Index -->
        <dt style="@termStyle">@Html.DisplayNameFor(m => m.MelodyTrackIndex)</dt>
        <dd>  @Model.MelodyTrackIndexDescription </dd>

        <!-- Created -->
        <dt style="@termStyle"> @Html.DisplayNameFor(m => m.Created)</dt>
        <dd>  @Model.Created.ToString("F", timeStampCulture) </dd>

        <!-- Modified -->
        <dt style="@termStyle"> @Html.DisplayNameFor(m => m.Modified)</dt>
        <dd>  @Model.Modified.ToString("F", timeStampCulture) </dd>
    </dl>
</div>

<!-- MIDI Tracks Table -->
<div>
    @{
        if (Model.MidiData != null)
        {
            <button type="button" class="collapsible" style="@collapseStyle">Display/Toggle MIDI Tracks</button>
            <div style="display:none">
                <table class="table table-bordered table-responsive table-hover">
                    <thead>
                        <tr style="color:gold">
                            <th> Track Number </th>
                            <th> Track Name </th>
                            <th> Instrument Description </th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 1; i < Model.MidiData.Tracks.Count; i++)
                        {
                            var track = Model.MidiData.Tracks[i];
                            <tr>
                                <td> @track.TrackNumber </td>
                                <td> @track.TrackName </td>
                                <td> @track.InstrumentName </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <br /> <br />
        }
    }
</div>

<!-- Chord Progression Text Area -->
<div>
    @{
        if (!string.IsNullOrEmpty(Model.ChordProgression))
        {
            <button type="button" class="collapsible" style="@collapseStyle">Display/Toggle Chord Progression</button>
            <div style="display:none">
                @Html.TextAreaFor(m => m.ChordProgression, 16, 80, new { @class = "green-border-focus", Style = "max-width: 40%; overflow=auto;", Spellcheck = "false", Readonly = true });
            </div>
        }
    }
</div>

<!-- Footer Links -->
<div>
    <footer>
        <br /><br />
        <p>
            <!-- Compose -->
            <text> || </text>
            @Html.ActionLink("Compose ♫♪", "Compose", "Composition", new { songId = Model.Id }, null)
            <text> || </text>

            <!-- Edit -->
            @if (Model.IsUserAuthorizedToEdit)
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) <text>||</text>
            }

            <!-- Delete -->
            @if (Model.IsUserAuthorizedToDelete)
            {
                @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) <text>||</text>
            }

            <!-- Index -->
            @Html.ActionLink("Back to Song List", "Index") <text>||</text>
        </p>
    </footer>
</div>

<!-- js logic for handling collapisble elements -->
<script>
    let collapsibleElement = document.getElementsByClassName("collapsible");
    let i;

    for (i = 0; i < collapsibleElement.length; i++) {
        collapsibleElement[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            }
            else {
                content.style.display = "block";
            }
        });
    }
</script>

WebApplication/Views/Songs/Index.cshtml
@using CW.Soloist.WebApplication.Controllers;
@model IEnumerable<SongViewModel>

@{
    ViewBag.Title = "Song Index";
    IPrincipal user = User;
    CultureInfo timeStampCulture = CultureInfo.CreateSpecificCulture("es-ES");
}

<!-- Header Title -->
<div>
    <h2 style="color:lightgreen">@ViewBag.Message</h2>
    <h1 style="color:greenyellow">@ViewBag.Title</h1>
</div>

<!-- New Song Button -->
<div>
    @Html.ActionLink("Upload a New Song", "Create", null, new { @class = "btn btn-warning btn-md" })
</div>

<!-- Song List -->
<div>
    <table class="table">
        <!-- tables headers -->
        <thead>
            <tr style="color:yellow">
                <th>  @Html.DisplayNameFor(model => model.Artist)  </th>
                <th>  @Html.DisplayNameFor(model => model.Title) </th>
                <th>  @Html.DisplayNameFor(m => m.Created) </th>
                <th>  @Html.DisplayNameFor(m => m.Modified) </th>
            </tr>
        </thead>

        <!-- tables contents -->
        <tbody>

            @foreach (var song in Model)
            {
                <tr>
                    <td> @Html.DisplayFor(m => song.Artist)  </td>
                    <td> @Html.DisplayFor(m => song.Title) </td>
                    <td> @song.Created.Date.ToString("d", timeStampCulture)</td>
                    <td> @song.Modified.ToString("d", timeStampCulture) </td>

                    <!-- action links -->
                    <td>
                        @{
                            <!-- Compose a New Melody For This Song -->
                            <text> || </text>
                            @Html.ActionLink("Compose ♫♪", "Compose", "Composition", new { songId = song.Id }, null)
                            <text> || </text>

                            <!-- Details -->
                            @Html.ActionLink("Details", "Details", new { id = song.Id }) <text> || </text>

                            <!-- Edit -->
                            if (song.IsUserAuthorizedToEdit)
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = song.Id }) <text> || </text>
                            }
                            else
                            {
                                <text> Edit ||</text>
                            }

                            <!-- Delete -->
                            if (song.IsUserAuthorizedToEdit)
                            {
                                @Html.ActionLink("Delete", "Delete", new { id = song.Id }) <text> || </text>
                            }
                            else
                            {
                                <text> Delete || </text>
                            }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>